### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by morlac** [eadf/esp_mqtt_lcd#2]
Hi,
currently I get this error when I try to compile (on Linux):

```
make clean && make
CC driver/stdout.c
CC pcd8544/driver/easygpio/easygpio.c
CC pcd8544/driver/pcd8544/pcd8544.c
CC mqtt/mqtt/mqtt.c
CC mqtt/mqtt/ringbuf.c
CC mqtt/mqtt/mqtt_msg.c
CC mqtt/mqtt/queue.c
CC mqtt/mqtt/proto.c
CC mqtt/mqtt/utils.c
CC user/user_main.c
user/user_main.c:33:18: fatal error: wifi.h: No such file or directory
 #include "wifi.h"
                  ^
compilation terminated.
Makefile:129: recipe for target 'build/user/user_main.o' failed
make: *** [build/user/user_main.o] Error 1
```

**Comment by eadf** [comment]
ok, i see what happened. 
The mqtt project moved wifi.\* and config.\* back into his user 'module'. 
My makefile can't add mqtt/user to MODULES, since then there will be two user_init() functions.
I should have tested this before just pulling the mqtt changes, sorry.
I will try to make a workaround for this.

...

Ok, fixed
